version: "3.3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  golang-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"